### ISSUE TITLE
GPA procedure changes Reference in DataCollection

### ISSUE THREAD

**Issue by marcelluethi** [unibas-gravis/scalismo#175]
The reference mesh of a DataCollection is set to the Procrustes mean when performing a GPA. 

Hence the following code returns false
```
val dc :  DataCollection = ???
val dcAfterGPA = DataCollection.gpa(dc)
dc.reference == dcAfterGPA.reference // false
```

I would argue that this is unintuitive and that only the transformations should change.

**Comment by Andreas-Forster** [comment]
I think this is perfectly fine as it is, as for gpa the steps are:

1. choose reference
2. align all shapes to reference
3. compute mean shape
4. if mean and reference are different, set mean as reference and continue with 2.

Hence this algorithm clearly changes the reference. If one does not want to have a new reference one should create a new DataCollection with the aligned data but a different reference.

**Comment by marcelluethi** [comment]
In traditional shape modelling I would agree with you. However, in scalismo (and the Gaussian process framework) we usually regard the reference simply as the domain over which the deformation fields / transformations are defined, and do not assign a semantic meaning to it (such as that the reference is the mean shape). While GPA clearly changes the mean, it does not change the domain over which the deformations are defined.

**Comment by Andreas-Forster** [comment]
I see your point, but then a different name should be introduced for this functionality. I think it is not a good idea to use widely used concepts and then change their behavior slightly without changing the name too. This makes it much more confusing for others to start with.

**Comment by marcelluethi** [comment]
I completely agree. The concept of the DataCollection in general is a bit difficult to grasp in the shape modelling context. Maybe we can simplify it in future versions.
