### ISSUE TITLE
Bug in computation of covariance matrix (MultivariateNormalDistribution)

### ISSUE THREAD

**Issue by marcelluethi** [unibas-gravis/scalismo#204]
One way of creating a MultivariateNormalDistribution is by specifying the mean and three orthonormal directions (with associated variance) (see https://github.com/unibas-gravis/scalismo/blob/master/src/main/scala/scalismo/statisticalmodel/MultivariateNormalDistribution.scala#L159) 

The computation does not compute the correct covariance matrix.

**Comment by sschoenborn** [comment]
Fixed in #205
