### ISSUE TITLE
ASM Fitting : findBestMatchingPointAtPoint can return 0 points.

### ISSUE THREAD

**Issue by ghost** [unibas-gravis/scalismo#21]
In ASM fitting findBestMatchingPointAtPoint can return 0 points if the filter values maxIntensityStddev and maxShapeStddev are too low. 

```scala
if (minIntensityDist < config.maxIntensityStddev && shapeDistForPt < config.maxShapeStddev) Some(minPt) else None
```

This leads to an error when 0 training data is used to get the coefficients of the shape model.

```scala
val coeffs = asm.shapeModel.coefficients(refPtIdsWithTargetPt, sigma2 = 1e-6)
```

**Comment by clangguth** [comment]
Fixed in be59ec5c49d5616a78d04f4ee7a411fc8638abf0: the fit methods now explicitly return a Failure in that case.
