### ISSUE TITLE
MorphableModel missing

### ISSUE THREAD

**Issue by elliotresearcher** [unibas-gravis/scalismo#215]
I have downloaded basel face database. Please guide me how to download "01_MorphableModel.mat" file. it is not available on basel website.
i am waiting for your kind reply.
thanks

**Comment by marcelluethi** [comment]
Once you have registered on
http://faces.cs.unibas.ch/bfm/?nav=1-2&id=downloads
you should receive an email with detailed instructions.

In case you have further question, please contact bernhard.egger@unibas.ch. Please do not open further issue on github.
