### ISSUE TITLE
Recompile VTK library to allow to be run headless 

### ISSUE THREAD

**Issue by madsendennis** [unibas-gravis/scalismo#232]
Update the VTK library to the newest version. This will allow running headless mode - thereby avoiding X forwarding.

**Comment by marcelluethi** [comment]
This would be an important contribution - not only for the reason you mention. It would also allow scalismoLab to benefit from improved rendering, and give us access to the new mesh and image processing methods in VTK. 

I would estimate that it takes around 2 days of work, including the testing.

**Comment by marcelluethi** [comment]
As we are using [vtk java wrapper](https://github.com/jzy3d/vtk-java-wrapper) this issue is no longer in the hands of the scalismo developers.
