### ISSUE TITLE
normalization of the huber loss

### ISSUE THREAD

**Issue by Ghazi-Bouabene** [unibas-gravis/scalismo#260]
Why is the lossfunction value in the Mean Huber Loss normalized by (1 + v * v)? 

https://github.com/unibas-gravis/scalismo/blob/610185a57a6eb56a62003fb421b3528b492b8580/src/main/scala/scalismo/registration/MeanHuberLossMetric.scala#L40

This differs from the classical definition of the Huber Loss https://en.wikipedia.org/wiki/Huber_loss

and creates a discontinuity since (v * v / 2) / (1 + v * v) and  (delta * (Math.abs(v) - delta / 2)) have different values for v = delta.

(Also, in practice, the current implementation does not seem to work for me, while changing it to the classical definition does).

**Comment by marcelluethi** [comment]
This is a bug. The denominator should not be there. If the denominator is removed, it also becomes consistent with the derivative.

**Comment by Andreas-Forster** [comment]
I fully agree that we should remove this denominator.

Is the function or a similar funtion `(v * v) / (1 + v * v)` in our code base? Was it maybe used somewhere due to its properties?

- quadratic when v is close to zero
- constant 1 when v is far away from zero
