### ISSUE TITLE
'instance' method from StatisticalMeshModel.java is too slow

### ISSUE THREAD

**Issue by nevenp** [unibas-gravis/scalismo#289]
Method 'instance' from StatisticalMeshModel.java is a little bit slow for my needs -> it takes a couple of milliseconds to execute. Is it possible to accelerate it somehow, using parallelization and/or using hardware acceleration (GPU)?

**Comment by marcelluethi** [comment]
the `instance` method it is linear in the number of mesh points and the number of basis function of the model. The simplest way to speed it up is to reduce the mesh resolution or the number of basis functions. The number of basis functions can be reduced with ```model.truncate(numBasisFunctions)```.
There is also a method to reduce the number of points on which the model is defined. But it is only available in the development version (see
https://github.com/unibas-gravis/scalismo/blob/develop/src/main/scala/scalismo/statisticalmodel/StatisticalMeshModel.scala#L199 ). 

Currently there is no plan to do a GPU implementation, as this would make it a lot more complicated to maintain scalismo.

**Comment by marcelluethi** [comment]
I am closing this issue, as it is not really a  problem we will be working on. 
If you have further question regarding this issue, we could move discussion to the mailing list.

**Comment by nevenp** [comment]
Thank you for the answer.
