### ISSUE TITLE
Points sampled inside tetrahedron not always inside

### ISSUE THREAD

**Issue by kahrpatrick** [unibas-gravis/scalismo#299]
I noticed that points returned by  `samplePointInTetrahedralCell` are sometimes outside of a cell.
The following test currently fails:

`implicit val rng = Random(42L)`

`it("points sampled inside a tetrahedron should not be outise of tetrahedron") {
      val tetrahedralMesh = createTetrahedronsInUnitCube()
      val cell = tetrahedralMesh.tetrahedralization.tetrahedron(TetrahedronId(0))
      val point =  tetrahedralMesh.samplePointInTetrahedralCell(cell)
      assert(tetrahedralMesh.isInsideTetrahedralCell(point, cell))
 }`

**Comment by rassaire** [comment]
I have defined a new sampler and tested and it works well. 

def samplePointInTetrahedralCell(tc: TetrahedralCell)(implicit rnd: Random): Point[_3D] = {
    val A = pointSet.point(tc.ptId2) - pointSet.point(tc.ptId1)
    val B = pointSet.point(tc.ptId3) - pointSet.point(tc.ptId1)
    val C = pointSet.point(tc.ptId4) - pointSet.point(tc.ptId1)


    var s = rnd.scalaRandom.nextDouble()
    var t = rnd.scalaRandom.nextDouble()
    var u = rnd.scalaRandom.nextDouble()

    while (s + t + u > 1) {
      s = rnd.scalaRandom.nextDouble()
      t = rnd.scalaRandom.nextDouble()
      u = rnd.scalaRandom.nextDouble()

    }
    pointSet.point(tc.ptId1) + (A * s + B * t + C * u)

  }

Let me know whether it works for your example.

**Comment by kahrpatrick** [comment]
Thanks! I checked it and it works for me. Let's get this into develop as soon as possible.

**Comment by rassaire** [comment]
Do I do a pull request for this? @marcelluethi

**Comment by marcelluethi** [comment]
Yes, please do a PR. No new code should ever get merged into scalismo without a PR and a review. 
As reviewers I would add Andreas and Patrick.
