### ISSUE TITLE
It is very helpful if scalismo have axis shown

### ISSUE THREAD

**Issue by Zju-George** [unibas-gravis/scalismo#308]
One can move a landmark point on each axis respectively or change 3D view to X Y Z to know the axis direction，but it is not convenient nor intuitive, I hope you can add this very helpful feature.
It is not hard,right?

**Comment by marcelluethi** [comment]
Hi Zju-George, 

I don't understand exactly the problem your describing and the solution you propose. Could you explain it a bit in more depth, maybe by first describing the durrent behaviour and then what would be the desired behaviour.

Also, it seems that the feature you are requesting is a feature of the ui. For this we have a separate [github repository](https://github.com/unibas-gravis/scalismo-ui). Please open the issue there. I will close it in this repository.

**Comment by Zju-George** [comment]
I mean this kind of 3D axes :joy::joy:! [image](https://user-images.githubusercontent.com/33959089/70694067-b9ed6a00-1cf9-11ea-91e5-90eb83bbd5f8.png)

**Comment by marcelluethi** [comment]
I see. I don't know how difficult it is but we can look into it.  It would, however, still be good if you could describe the issue on the scalismo-ui repo.
