### ISSUE TITLE
Instability in PivotedCholesky

### ISSUE THREAD

**Issue by skylar-sutherland** [unibas-gravis/scalismo#309]
There seems to be an issue with the PivotedCholesky, in that for many input computeApproximateEig demonstrates chaotic behavior, i.e. a tiny variation in the input produces large variation in the output.  This is not a matter of indeterminacy; the code is deterministic, it is just sensitive to tiny variations of input.  Here is some code to demonstrate this:

`
val p2ds = for (_ <- 0 until 10) yield Point[_2D](DenseVector.rand[Double](2).toArray)
val variancesA = (DenseVector.rand[Double](100) / 10.0).toArray.toIndexedSeq
val variancesB = for (v <- variancesA) yield v + 1e-15  // without the +1e-15, the difference is 0.0
val gk2ds = for (s <- variancesA ++ variancesB) yield GaussianKernel[_2D](s)
val ik2ds = for (k <- gk2ds) yield DiagonalKernel(k, 3)
val tol = PivotedCholesky.RelativeTolerance(1e-12)
val (dms, dvs) = (for (ik <- ik2ds) yield PivotedCholesky.computeApproximateEig(ik, p2ds, 0.5, tol)).unzip
val dmdiffs = for (i <- 0 until 100) yield (dms(i + 100) - dms(i)).toArray.toIndexedSeq
val dvdiffs = for (i <- 0 until 100) yield (dvs(i + 100) - dvs(i)).toArray.toIndexedSeq
println((for (x <- dmdiffs.flatten ++ dvdiffs.flatten) yield math.abs(x)).sum)
`

Note that this test code is random and does not always demonstrate the instability, but usually does.  Furthermore, the instability itself does not necessarily make an error in the result of the computation using PivotedCholesky.  But whether or not the instability directly produces an error in the output, it seems an undesirable property of PivotedCholesky, particularly since it makes the generation of LowRankGaussianProcesses effectively randomized in practice.

Thanks for sharing your code.

**Comment by marcelluethi** [comment]
Thanks for letting us know. This should not be the case. We will look into it to see what is going on.

**Comment by BernhardEgger** [comment]
Dear Scalismo Team,
we were wondering if you already had a look at this issue?
Best
Bernhard

**Comment by marcelluethi** [comment]
Hi Bernhard, 

Thanks for following up on this and sorry for not responding. This bug slipped our attention. 

I have done preliminary investigations and first evidence indicates that it is not the problem of the pivoted cholesky, but the svd that is used afterwards to compute the eigenvalues. Can you confirm on your side that when you use ```PivotedCholesky.computeApproximateCholesky[_2D,_2D](ik, p2ds, tol)``` that it works as expected? 

If this is the case, then we have the next task at hand to figure out why our back-end  library (which uses blas/lapack) is sometimes numerically not stable. We have observed such issues before and it would be a good opportunity to fix this once and for all.

**Comment by marcelluethi** [comment]
Thanks for trying this out. 

It is now clear. It is an instability in the SVD implementation, which comes from a downstream library. Currently we are relying on a generic, java based implementation of BLAS/LAPACK. The solution could be to ship native implementations of BLAS and LAPACK. (see [this page](https://github.com/fommil/netlib-Java) for more information). This will, however, take some time before we are able to integrate and test it. 

How does that bug affect your work? Does it pose a real problem for the application or do you observe it only in these synthetic setting. If you see it in a real application, can you tell me how you define the kernel parameters and the domain?
