### ISSUE TITLE
Scalismo Lab

### ISSUE THREAD

**Issue by viliusmat** [unibas-gravis/scalismo#355]
Hello, I have noticed, that link to Scalismo Lab is broken. Is there an alternative way to obtain it?

**Comment by marcelluethi** [comment]
Hi, Thanks for reporting this. Can you point me to the page where the link is broken? We had links from many different pages and I am not sure which one you mean.

**Comment by viliusmat** [comment]
Thanks for your reply. Here is the link: https://github.com/unibas-gravis/scalismo/wiki/scalismoLab (Download the latest version of Scalismo Lab for Windows, MacOs or Linux) none of there work.

**Comment by marcelluethi** [comment]
Thanks. I see that this is a problem with a server that we recently moved. I will fix it as soon as possible, but as I am not in charge of the new server, this might take a day or two.

**Comment by marcelluethi** [comment]
It turned out that the webserver was down. It should now work again. 

Thanks again for reporting it.
