### ISSUE TITLE
IO : ncsa.hdf.hdf5lib Failure when call StatismoIO.writeStatismoMeshModel

### ISSUE THREAD

**Issue by fabricecarles** [unibas-gravis/scalismo#357]
Hi !
I’m new in scala and scalimo. I try to load and save again a model like this: 
```
val model = StatismoIO.readStatismoMeshModel(new File("datasets/bfm.h5")).get
show(model, "model")
StatismoIO.writeStatismoMeshModel(model, new File("dataset/testModelOutput.h5"))
```
but I get : `res25: scala.util.Try[Unit] = Failure(ncsa.hdf.hdf5lib.exceptions.HDF5LibraryException)`
Why can I load the model from hdf5 but can't write it again ? 

I follow installation instruction from this tutorial : https://www.futurelearn.com/courses/statistical-shape-modelling/4/steps/412709 (and make a `chmod +x *` in bin directory before running GUI with ./scalismolab.sh)

Is there a problem with my version ? 

scalismo 0.10.0, scala 2.11.7
openjdk version "1.8.0_272"
OpenJDK Runtime Environment (build 1.8.0_272-8u272-b10-0ubuntu1~16.04-b10)
OpenJDK 64-Bit Server VM (build 25.272-b10, mixed mode)

**Comment by marcelluethi** [comment]
Hi 

We are not aware of any issue with writing models. Also the fact that you can read the model means that loading the necessary native libraries does work. Is it possible that you for some reason do not have the rights to write into the directory or the directory does not exist?

Can you try calling
```StatismoIO.writeStatismoMeshModel(model, new File("dataset/testModelOutput.h5")).get```
instead and post the stack trace that results from that?

**Comment by fabricecarles** [comment]
Hi, 
Thanks this was indeed an access write issue.

Since 2020 I have also updated scalismo version and now it work, I can load and save again the bfm.h5 model by adding `writeStatisticalTriangleMeshModel3D`
```scala
val model =   StatisticalModelIO.readStatisticalTriangleMeshModel3D(new java.io.File("datasets/bfm.h5")).get
// write this model in new .h5 file 
  StatisticalModelIO.writeStatisticalTriangleMeshModel3D(model, new java.io.File("/home/fabrice/testOutputBFM.h5")).get
```
