### ISSUE TITLE
Error in LogPdf computation of MVND

### ISSUE THREAD

**Issue by madsendennis** [unibas-gravis/scalismo#371]
The `logpdf` function in the `MultivariateNormalDistribution` fails to correctly compute the logpdf in cases where a large covariance matrix is defined with a small variance. 
In such a case the normFactor is not numerical stable. 

An example of this is a diagonal matrix with a std. dev < 1.0 and a rank > 50:
 
```scala
 val stdDev = 0.1
 val model = myMVND(DenseVector.zeros[Double](100), DenseMatrix.eye[Double](100)*stdDev*stdDev)
 model.logpdf(DenseVector.zeros[Double](100))
```
this gives -80.38 

With `scipy` in `python`, the output is instead 138.36

**Comment by JonathanAellen** [comment]
We could create a fix for diagonal covariance matrices fairly easily by directly computing the log of the normFactor. That means the current implementation
```scala
val normFactor = math.pow(2.0 * math.Pi, -dim / 2.0) * 1.0 / math.sqrt(covDet + 1e-10)
//...
math.log(normFactor) + exponent
```
could be replaced with 
```scala
//if cov matrix diagonal
val logNormFactor = -0.5 * (dim * math.log(2.0 * math.Pi) + diag(cov).toArray.map(math.log).sum)
//...
logNormFactor + exponent
```

**Comment by marcelluethi** [comment]
This solutions looks good to me. Would you have time to prepare a PR (to develop?)
