### ISSUE TITLE
Shouldn't the log transition probability depend on the induced change?

### ISSUE THREAD

**Issue by Andreas-Forster** [unibas-gravis/scalismo#385]
Not sure if I completely oversee something, but shouldn't the log transition probability depend on the change that the sample induced?
https://github.com/unibas-gravis/scalismo/blob/1d7137171101c84ce9912bb30eb82d2e149fc525/src/main/scala/scalismo/sampling/proposals/GaussianRandomWalkProposal.scala#L45

I would expect that it depends on something like (to.parameters-from.parameters) as larger changes should usually have a smaller transition probability than smaller once.

**Comment by marcelluethi** [comment]
Nice catch, thanks. Indeed, this computation was nonsense. 

I just pushed a fix, which hopefully yields the correct transitionprobability.
