### ISSUE TITLE
Slow triangular mesh boundary calculation for large meshes

### ISSUE THREAD

**Issue by madsendennis** [unibas-gravis/scalismo#413]
For large meshes (+100K vertices), the current calculation `TriangularMeshBoundaryPredicates` is slow. 
E.g. a 400K vertice mesh can end up taking +30 seconds.

From debugging, it seems that the slow computation is from a continuous update of a `CSCMatrix[Boolean]`:
```
    triangles.foreach { triangle =>
      edgesOfATriangle.foreach { edge =>
        val v1 = triangle.pointIds(edge._1).id
        val v2 = triangle.pointIds(edge._2).id
        edgeOnBorderTmp(v1, v2) = !edgeOnBorderTmp(v1, v2)
        edgeOnBorderTmp(v2, v1) = !edgeOnBorderTmp(v2, v1)
      }
    }
```

**Comment by marcelluethi** [comment]
This issue has been resolve (PR #414 ) and published as v0.92.1
