### ISSUE TITLE
Error when reading saved StatisticalMeshModel file

### ISSUE THREAD

**Issue by AgentKu** [unibas-gravis/scalismo#430]
Hello, I am interested in your approach. However, I'm having some problems with it and would like to ask for your guidance!

Specifically, after I generate a StatisticalMeshModel based on a referenceMesh and a DiscreteLowRankGaussianProcess, I use StatismoIO.writeStatismoMeshModel to save as an h5 model file. Then I read that StatisticalMeshModel in another file showing **No valid HDF5 signature found**.
![截图 2024-09-13 14-33-36](https://github.com/user-attachments/assets/6cf3f1a7-48ba-493b-bd17-8b0be2d26db5)

The same problem occurs when I try to read and write an existing h5 model file.
![图片](https://github.com/user-attachments/assets/0407309c-0244-41d0-b6b4-11e309bfe283)

Do you have any ideas on how to solve this problem? Or is there something wrong in my code？

**Comment by madsendennis** [comment]
Hi @AgentKu, in newer versions of Scalismo, the direct .h5 writing has been removed to remove a dependency on an external Java library. 

The model is written out in h5json format.
Example:
```scala
StatismoIO.writeStatisticalTriangleMeshModel3D(pdm, new File("pdm.h5.json"))
val pdmRead = StatismoIO.readStatisticalTriangleMeshModel3D(new File("pdm.h5.json")).get

```
It is, however, still possible to read valid .h5 files Scalismo.

In your example, you should not `.get` when writing the model. 

If you want to convert the saved h5json to an h5 file, you can use an external library, e.g., https://hdf5-json.readthedocs.io/en/latest/tools/h5json.html.
