### ISSUE TITLE
Conversion from Signed Char image fails with ClassCastException

### ISSUE THREAD

**Issue by marcelluethi** [unibas-gravis/scalismo#69]
The following code
```
 case VTK_CHAR | VTK_SIGNED_CHAR =>
         val in = arrayVTK.asInstanceOf[vtkCharArray].GetJavaArray()
```
results in a classCastException as a```vtkSignedCharArray``` cannot be cast into 
a ```vtkCharArray```. A solution would be to treat the cases ```VTK_CHAR``` and ```VTK_SIGNED_CHAR``` separately.

**Comment by clangguth** [comment]
Fixed in commit 5654011
