### ISSUE TITLE
LowRankGaussianProcess.approximateGP returns GPs that behave differently to the same coefficients

### ISSUE THREAD

**Issue by Ghazi-Bouabene** [unibas-gravis/scalismo#9]
This is due to the RandomSVD approximation behaving differently at each call. A temporary solution on the course branch was to seed the random generator.

**Comment by marcelluethi** [comment]
My initial hope was that the "randomness" in RandSVD is hidden from the rest of the system (as it provides an approximation to a deterministic quantity). After some tests it seems that we cannot count on it, and the estimation of the eigenfunction varies quite a bit. 

Interestingly, we we do an SVD on complely random matrices, the estimation is almost perfect. 
For our matrices (obtained from a Gaussian Kernel) there is quite a lot of variation. Maybe we can get more insight from the original paper. If not, we need to add the seed or switch to another method for computing the svd (I have seen that mllib packages an arnoldi method, which could be used for the computation of the leading eigenvectors).

**Comment by marcelluethi** [comment]
Fixed, as we are now using the Pivoted Cholesky to compute the eigendecomposition in the Nystrom method (see #112, #176 ).
