### ISSUE TITLE
Harmonize IO methods

### ISSUE THREAD

**Issue by Ghazi-Bouabene** [unibas-gravis/scalismo#97]
currently Landmark IO methods are generic and rely on type parameters : readLandmarksJson[_3D]
On the other hand, image reading methods are named differently for different dimensionality: read3DScalarImage

Ideally, one of the approaches should be used for both Landmarks and Images; preferably,  generic methods for both cases.

**Comment by marcelluethi** [comment]
This issue was addressed in a previous scalismo version. I will therefore close this issue.
